# Generated by Django 4.2.3 on 2025-07-18 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='responsible_senior_barista',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'senior_barista'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_shops', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный старший бариста'),
        ),
    ]
