# Generated by Django 4.2.3 on 2025-07-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coffee_count',
            field=models.IntegerField(default=0, verbose_name='Количество кофе'),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_spent',
            field=models.IntegerField(default=0, verbose_name='Общий чек (в копейках)'),
        ),
    ]
