# Generated by Django 4.2.3 on 2025-07-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_coffee_count_user_points_user_total_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='opening_hours',
            field=models.JSONField(blank=True, help_text="Формат: {'0': {'open': '09:00', 'close': '22:00'}, ...}", null=True, verbose_name='Часы работы'),
        ),
    ]
