# Generated by Django 4.2.3 on 2025-08-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_coffeeshop_latitude_coffeeshop_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ранга')),
                ('min_total_spent_som', models.IntegerField(verbose_name='Минимальная сумма, сом')),
                ('cashback_percent', models.IntegerField(verbose_name='Кэшбек, %')),
                ('icon_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='URL PNG иконки')),
            ],
            options={
                'verbose_name': 'Ранг',
                'verbose_name_plural': 'Ранги',
                'ordering': ['min_total_spent_som'],
            },
        ),
    ]
