# Generated by Django 4.2.3 on 2025-08-12 07:11

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='rank',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=18, samples=None, verbose_name='Цвет ранга (HEX)'),
        ),
        migrations.AddField(
            model_name='rank',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='ranks/', verbose_name='Иконка'),
        ),
    ]
