# Generated by Django 4.2.3 on 2025-07-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltycode',
            name='is_free_coffee_redemption',
            field=models.BooleanField(default=False, verbose_name='Код для получения бесплатного кофе'),
        ),
    ]
