# Generated by Django 4.2.3 on 2025-07-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_loyaltycode_is_free_coffee_redemption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltytransaction',
            name='points',
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='points_earned',
            field=models.IntegerField(default=0, verbose_name='Начислено бонусов'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='points_used',
            field=models.IntegerField(default=0, verbose_name='Использовано бонусов'),
        ),
    ]
