# Generated by Django 4.2.3 on 2025-08-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('idea', 'Предложение идеи'), ('service', 'Отзыв об обслуживании')], default='service', max_length=20, verbose_name='Тип отзыва'),
        ),
    ]
