# Generated by Django 4.2.3 on 2025-07-22 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='volume',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена (за базовую порцию)'),
        ),
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название порции')),
                ('volume', models.PositiveIntegerField(verbose_name='Объём')),
                ('unit', models.CharField(default='мл', max_length=10, verbose_name='Единица измерения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='menue.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Порция',
                'verbose_name_plural': 'Порции',
                'unique_together': {('category', 'name', 'volume', 'unit')},
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='portions',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='menue.portion', verbose_name='Доступные порции'),
        ),
    ]
