# Generated by Django 4.2.3 on 2025-07-22 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menue', '0002_remove_menuitem_volume_alter_menuitem_price_portion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='portions',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
        migrations.AlterUniqueTogether(
            name='portion',
            unique_together={('name', 'volume', 'unit')},
        ),
        migrations.RemoveField(
            model_name='portion',
            name='category',
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('is_default', models.BooleanField(default=False, verbose_name='Вариант по умолчанию')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='menue.menuitem', verbose_name='Товар')),
                ('portion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_variants', to='menue.portion', verbose_name='Порция')),
            ],
            options={
                'verbose_name': 'Вариант товара',
                'verbose_name_plural': 'Варианты товаров',
                'unique_together': {('menu_item', 'portion')},
            },
        ),
    ]
