# Generated by Django 4.2.3 on 2025-08-12 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menue', '0003_remove_menuitem_portions_remove_menuitem_price_and_more'),
        ('core', '0006_coffeeshop_latitude_coffeeshop_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('pickup', 'Забрать в кафе'), ('delivery', 'Доставка')], default='pickup', max_length=20, verbose_name='Тип получения')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта на месте'), ('online', 'Онлайн-оплата (заглушка)')], default='cash', max_length=20, verbose_name='Метод оплаты')),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('failed', 'Ошибка оплаты')], default='pending', max_length=20, verbose_name='Статус оплаты')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('accepted', 'Принят'), ('in_progress', 'Готовится'), ('ready', 'Готов к выдаче'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('items_total_amount', models.IntegerField(default=0, verbose_name='Сумма позиций (в коп.)')),
                ('discount_amount', models.IntegerField(default=0, verbose_name='Скидка (в коп.)')),
                ('final_amount', models.IntegerField(default=0, verbose_name='Итого к оплате (в коп.)')),
                ('customer_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий клиента')),
                ('delivery_address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес доставки')),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта доставки')),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.coffeeshop', verbose_name='Заведение')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=200, verbose_name='Название на момент покупки')),
                ('portion_snapshot', models.CharField(max_length=100, verbose_name='Порция на момент покупки')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('unit_price', models.IntegerField(verbose_name='Цена за единицу (в коп.)')),
                ('total_price', models.IntegerField(verbose_name='Сумма (в коп.)')),
                ('is_coffee', models.BooleanField(default=False, verbose_name='Кофе')),
                ('item_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menue.itemvariant', verbose_name='Вариант товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order', verbose_name='Заказ')),
            ],
        ),
    ]
