# Generated by Django 4.2.3 on 2025-08-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='planned_coffee_quantity',
            field=models.IntegerField(default=0, verbose_name='Плановое количество кофе'),
        ),
        migrations.AddField(
            model_name='order',
            name='planned_earn_points',
            field=models.IntegerField(default=0, verbose_name='План к начислению (в баллах)'),
        ),
        migrations.AddField(
            model_name='order',
            name='planned_points_to_spend',
            field=models.IntegerField(default=0, verbose_name='План к списанию (в баллах)'),
        ),
        migrations.AddField(
            model_name='order',
            name='planned_use_points',
            field=models.BooleanField(default=False, verbose_name='Планируется списание баллов'),
        ),
    ]
